language: node_js
node_js:
  - "0.11"
  - "0.10"
script: "grunt ci"

# setup U.I. for browser tests
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script: 
  - "npm install"
  - "npm install -g grunt-cli"
  - "npm install -g testem"
